version: '3.7'
services:
  nginx:
    build: .
    environment:
      NGINX_PORT: '8080'
      NGINX_HOST: http://10.117.110.121:8081
    stdin_open: true
    tty: true
    ports:
      - '8081:8080'
    volumes:
        - ./default.conf.template:/etc/nginx/conf.d/default.template